cs10703:
  destination: {host: 92.53.96.171, password: QvyMkRinXy8U, user: cs10703}
  domains: [truba-delo.ru]
  source: {host: u8595.netangels.ru, password: yWHu93rCERKcMMe, user: u8595}
  ticket: '3284075'
