zarstvoruk:
  destination: {host: 92.53.96.194, password: r2pk1wxmy5uZ, user: zarstvoruk}
  domains: [tkani-lifestyle.ru]
  source: {host: 176.57.210.35, password: 2uXSr68eb82g, user: cw98004}
  ticket: '3285677'
